name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Cambia 12.x por 20.x
        node-version: [20.x] 

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Esto acelera tus builds futuros
      
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  lint:
    name: Node Code Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Cambiamos el due√±o a 'root' que es quien suele ejecutar Docker
      - name: Fix workspace ownership
        run: sudo chown -R root:root $GITHUB_WORKSPACE

      - name: Node Code Formatter
        uses: MarvinJWendt/run-node-formatter@1.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
